### ISSUE TITLE
An error occurred when executing task "deps"

### ISSUE THREAD

**Issue by coolrecep** [OpenRA/ra2#371]
This is the error when I try to compile RA2:

![image](https://cloud.githubusercontent.com/assets/13221472/23587361/f3f74532-01b2-11e7-9771-6dd1634745f1.png)

**Comment by Fincer** [comment]
OpenRA.Mods.TS.dll got merged with OpenRA.Mods.Cnc.dll

https://github.com/OpenRA/OpenRA/commit/709e2a26e13b614f9a240734fd54a09e74eb6778

Though you may want compile the game yourself, I've coded a simple script for that (it's not perfect and needs a re-write but it does the job anyway). You may be interested in checking it out:

https://github.com/Fincer/openra-tibsunra2/

I hope this helps you.

**Comment by abcdefg30** [comment]
That should be fixed since a long time by https://github.com/OpenRA/ra2/commit/613ce6f52b58dd376d382ea1c969163da9fd5caa. Are you sure that you're using the latest master version of the RA2 mod?

**Comment by coolrecep** [comment]
OK. Passed that. Now stuck at here:

![image](https://cloud.githubusercontent.com/assets/13221472/23675732/f526f4ee-0382-11e7-95ea-6cb626fdf733.png)

**Comment by abcdefg30** [comment]
Ah right. That is my fault. The cnc dll was moved into the common folder recently. You can find it there and copy it manually until I push an update tomorrow, sorry for the inconvenience. ^^

**Comment by abcdefg30** [comment]
Wait, this was actually fixed in https://github.com/OpenRA/ra2/commit/deaeef56f90d55c403b2411ac76d61b34e2a200b. You might be running an outdated version of OpenRA.

**Comment by coolrecep** [comment]
OK, finally compiled the game. But OpenRA does not recognize it. Or I am doing something wrong.

![image](https://cloud.githubusercontent.com/assets/13221472/23826302/7a541846-06a2-11e7-95c7-e0a87eb06eca.png)


![image](https://cloud.githubusercontent.com/assets/13221472/23826308/9984028a-06a2-11e7-8ae1-0f5dd7176677.png)

**Comment by abcdefg30** [comment]
The warnings are ok. It looks like you ran "make version" on your OpenRA install. Either revert that to `{DEV_VERSION}`, or change [this here](https://github.com/OpenRA/ra2/blob/master/mod.yaml#L8) to whatever version your OpenRA install has.

**Comment by coolrecep** [comment]
@Fincer , I have used your script and did everytnig fine but OpenRA still can not find the compiled game.

I even put git-0b49505 to mod.yaml but I am still getting the error in OpenRA:

Missing dependencies.

Please fully install the following mods then try again.

![openra 26 03 2017 20_04_55](https://cloud.githubusercontent.com/assets/13221472/24333388/aa0325f0-125f-11e7-9c86-75ca090f0bcf.png)

![image](https://cloud.githubusercontent.com/assets/13221472/24333390/b58ad5a8-125f-11e7-85bf-b0c38084e47e.png)

**Comment by coolrecep** [comment]
OK. Finally after removing ra2 from C:\Users\recep\Documents\OpenRA\mods helped!

**Comment by Fincer** [comment]
Yup, that's good to know. I'm glad you could solve the problem!
